# Generated by Django 4.1.1 on 2022-09-19 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_num",
                    models.CharField(max_length=13, unique=True, verbose_name="계좌번호"),
                ),
                ("account_name", models.CharField(max_length=45, verbose_name="계좌명")),
                (
                    "account_total",
                    models.IntegerField(default=0, null=True, verbose_name="계좌 총 자산"),
                ),
            ],
            options={"db_table": "accounts",},
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_name",
                    models.CharField(max_length=45, unique=True, verbose_name="종목명"),
                ),
                (
                    "isin",
                    models.CharField(max_length=45, unique=True, verbose_name="ISIN"),
                ),
                (
                    "asset_group",
                    models.CharField(max_length=45, unique=True, verbose_name="자산그룹"),
                ),
            ],
            options={"db_table": "stocks",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=45, verbose_name="유저이름")),
                (
                    "account",
                    models.OneToOneField(
                        default="0",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="user",
                        to="investment_mgt.account",
                    ),
                ),
            ],
            options={"db_table": "users",},
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="investment",
                        serialize=False,
                        to="investment_mgt.user",
                    ),
                ),
                ("brokerage", models.CharField(max_length=45, verbose_name="증권사")),
                (
                    "principal",
                    models.IntegerField(blank=True, null=True, verbose_name="투자원금"),
                ),
            ],
            options={"db_table": "investments",},
        ),
        migrations.CreateModel(
            name="UserHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_price",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="현재가"
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="investment_mgt.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_holdings",
                        to="investment_mgt.user",
                    ),
                ),
            ],
            options={"db_table": "user_holdings",},
        ),
    ]
