# Generated by Django 4.1.1 on 2022-09-19 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_mgt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_total",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="계좌 총 자산",
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="principal",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="투자원금",
            ),
        ),
        migrations.AlterField(
            model_name="userholding",
            name="current_price",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="현재가",
            ),
        ),
    ]
